"""Render research/baseline/metrics.json into research/reports/BASELINE.md."""

from __future__ import annotations

import json
from pathlib import Path

METRICS = Path("research/baseline/metrics.json")
OUT = Path("research/reports/BASELINE.md")
ARMS = ["B0", "B1", "B2", "B3", "B4", "B5", "ELO", "MARKET", "ENSEMBLE", "ESPN"]


def f(x: object, nd: int = 3) -> str:
    if x is None:
        return "—"
    try:
        return f"{float(x):.{nd}f}"  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return str(x)


def arm_table(res: dict, sample: str) -> list[str]:
    rows = [
        "| Arm | N | Margin MAE | Margin RMSE | Margin bias | Total MAE | Total RMSE | "
        "Total bias | Log loss | Brier | ECE |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for a in ARMS:
        r = res.get(sample, {}).get(a)
        if not r:
            continue
        if a == "ESPN":
            rows.append(
                f"| ESPN pregame WP | {r['wp'].get('n', 0)} | — | — | — | — | — | — | "
                f"{f(r['wp'].get('log_loss'), 4)} | {f(r['wp'].get('brier'), 4)} | "
                f"{f(r.get('ece'), 4)} |"
            )
            continue
        m, t, w = r["margin"], r["total"], r["wp"]
        rows.append(
            f"| {a} | {m.get('n', 0)} | {f(m.get('mae'))} | {f(m.get('rmse'))} | "
            f"{f(m.get('bias'))} | {f(t.get('mae'))} | {f(t.get('rmse'))} | "
            f"{f(t.get('bias'))} | {f(w.get('log_loss'), 4)} | {f(w.get('brier'), 4)} | "
            f"{f(r.get('ece'), 4)} |"
        )
    return rows


def bet_table(rows: list[dict]) -> list[str]:
    out = ["| Edge ≥ | Bets | Win % | 95% CI | ROI @ -110 |", "|---|---|---|---|---|"]
    for r in rows:
        out.append(
            f"| {r['edge_ge']:.0f} | {r['bets']} | {f(r['win_pct'] * 100 if r['bets'] else None, 1)} | "
            f"{f(r['ci95_lo'] * 100, 1)}–{f(r['ci95_hi'] * 100, 1)} | "
            f"{f(r['roi_at_-110'] * 100 if r['bets'] else None, 1)}% |"
        )
    return out


def main() -> None:
    m = json.loads(METRICS.read_text())
    lines = [
        "# Baseline walk-forward study",
        "",
        "Generated by `scripts/backtest/run_baseline.py` + `make_report.py`. Every projection",
        "is produced day by day from information available before tip-off (see",
        "`docs/LEAKAGE.md`). Fitted layers use only earlier seasons. Hyperparameters were",
        "tuned on DEV seasons 2007–2014 only.",
        "",
        f"Engine config: `{json.dumps(m['config'])}`",
        "",
    ]
    for split, title in (
        ("validation_2015_2024", "Validation 2015–2024"),
        ("holdout_2025_2026", "Holdout 2025–2026 (opened once, config frozen)"),
    ):
        res = m.get(split)
        if not res:
            continue
        lines += [
            f"## {title}",
            "",
            f"Completed D-I vs D-I games: {res['n_games']}; common sample (all arms "
            f"project): {res['n_common']}; with a free closing line: {res['n_with_lines']}.",
            "",
            "### All games (common sample)",
            "",
            *arm_table(res, "all"),
            "",
            "### Games with a free historical closing line",
            "",
            *arm_table(res, "with_lines"),
            "",
            "### Margin MAE by season",
            "",
            "| Season | N | B0 | B1 | B2 | B3 | B4 | B5 | ELO | N lines | B3 (lined) | MARKET |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|",
        ]
        for s, r in res["by_season_margin_mae"].items():
            lines.append(
                f"| {s} | {r['n']} | {f(r['B0'], 2)} | {f(r['B1'], 2)} | {f(r['B2'], 2)} | "
                f"{f(r['B3'], 2)} | {f(r['B4'], 2)} | {f(r['B5'], 2)} | {f(r['ELO'], 2)} | "
                f"{r['n_lines']} | {f(r.get('B3_on_lines'), 2)} | {f(r.get('MARKET'), 2)} |"
            )
        lines += ["", "### Against the spread vs free closing line (research only)", ""]
        for a, rows in res["ats_vs_close"].items():
            lines += [f"**{a}**", "", *bet_table(rows), ""]
        lines += ["### Totals vs free closing total (research only)", ""]
        for a, rows in res["totals_vs_close"].items():
            lines += [f"**{a}**", "", *bet_table(rows), ""]
        if "clv_open_to_close" in res:
            c = res["clv_open_to_close"]
            lines += [
                "### Open → close line movement (2026 DraftKings open/close only)",
                "",
                f"N = {c['n']}; corr(model edge vs open, open→close move) = "
                f"{f(c['corr_edge_vs_move'])}; share of moves toward the model when "
                f"|edge| ≥ 2: {f(c['share_move_toward_model_when_edge_ge_2'])} "
                f"(n = {c['n_edge_ge_2']}).",
                "",
            ]
        lines += [
            "### B3 win-probability calibration",
            "",
            "| Bin | N | Mean predicted | Observed |",
            "|---|---|---|---|",
        ]
        for r in res["calibration_B3"]:
            lines.append(f"| {r['bin']} | {r['n']} | {f(r['mean_pred'])} | {f(r['observed'])} |")
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
